"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PyOMlx.py']
DATA_FILES = ['LICENSE',
 'README.md',
 'prompt.py',
 'logo.jpeg',
 'logo.png',
 'requirements.txt',
 'serve.py',
 'serveTest.py']
OPTIONS = {'iconfile':'logo.icns', 'use_pythonpath' : True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
